Add tpm2
stackhpc/ansible-role-luks pull request #25
Opened 2022-06-30 20:02 UTC by oneswig

Support using an on-board TPM for encryption key storage.

2022-07-01 08:04 UTC, markgoddard requested changes

2022-07-01 08:04 UTC, markgoddard commented on README.md
> +==================
This ends up as a top-level heading. You could change the actual top-level heading to be like this:


```
====
luks
====
```

Or use a different character here

2022-07-01 08:04 UTC, markgoddard commented on README.md
> +Setting options for `/etc/crypttab` can be useful if an encrypted
Doesn't say how to specify options.

2022-07-01 08:04 UTC, markgoddard commented on tasks/install.yml
> +        required: "{{ luks_devices | selectattr('mode', 'defined') | selectattr('mode', 'in', 'tang,tpm2') | list | length > 0 }}"
nit: I expect this is doing a substring search, whereas this would match on the full string:

```
selectattr('mode', 'in', [''tang', 'tpm2'])
```

2022-07-01 08:04 UTC, markgoddard commented on tasks/install.yml
> +        required: "{{ luks_devices | selectattr('mode', 'defined') | selectattr('mode', 'in', 'tpm2') | list | length > 0 }}"
`s/in/equalto/`

2022-07-01 08:04 UTC, markgoddard commented on tasks/tpm2.yml
> +---
Logic looks ok, can't really validate the clevis stuff

2022-08-08 08:03 UTC, markgoddard approved these changes, later dismissed

2022-08-08 08:03 UTC, markgoddard commented
Merge conflict in the README

2023-05-02 14:36 UTC, jovial approved these changes

2023-05-02 14:36 UTC, merged